### ISSUE TITLE
ユーザーが同一選手を複数登録できないようにする

### ISSUE THREAD

**Issue by KishiKyousuke** [KishiKyousuke/prospects_watcher#9]
現状だとユーザーが一人の選手を何度も登録できてしまうため。

**Comment by yusuke-matsuda** [comment]
![スクリーンショット 2020-12-23 16 04 10](https://user-images.githubusercontent.com/8966498/102969313-d3460a80-4538-11eb-8457-f1db265ce118.jpg)
別ブラウザで同時に実行すると登録出来てしまう
